# -*- coding: utf-8 -*-
"""estatistica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vqlH6HgNuoVtro_IRdRTJehU-7Nzr4a-
"""

import numpy

import statistics

import math


def desviopadrao():
  
        colecao = [2, 4, 6, 8, 10]

        list_elevado = []

        quadrado = []
        
        media = sum(colecao)/len(colecao)

        print(f'\nA média é: {media:.2f}')

        for numero in colecao:

          numero_menos_media = numero - media

          quadrado.append(numero_menos_media)

          print(f'\nA diferença é: {numero_menos_media:.2f}')

        for elevado in quadrado:

          elevar = elevado**2

          list_elevado.append(elevar)

          print(f'\nO quadrado é: {elevar:.2f}')

        variancia = sum(list_elevado)/len(colecao)

        print(f'\nA variância é: {variancia:.2f}')

        desvio_padrao = math.sqrt(variancia)

        print(f'\nO desvio padrão é: {desvio_padrao:.2f}')

desviopadrao()